imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.pages_backoffice:
        accueil:
            nom: 'Accueil'
            niveau: 'ROLE_MEMBER_EXPIRED'
        membres:
            nom: 'Membres'
            niveau: 'ROLE_ADMIN'
            icon: 'user'
            elements:
                personnes_physiques:
                    nom: 'Personnes physiques'
                    niveau: 'ROLE_ADMIN'
                personnes_morales:
                    nom: 'Personnes morales'
                    niveau: 'ROLE_ADMIN'
                relances_personnes_physiques:
                    nom: 'Relances cotisations'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/association/relances/1'
                reporting:
                    nom: 'Reporting'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/reporting'
                badges:
                    nom: 'Badges'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/badges'
                assemblee_generale:
                    nom: 'Assemblée générale'
                    niveau: 'ROLE_ADMIN'
                membres_liste:
                    nom: 'Annuaire'
                    niveau: 'ROLE_ADMIN'
        veille:
            nom: "Veille"
            niveau: "ROLE_VEILLE"
            icon: 'bullhorn'
            elements:
                veille_ generer_campagne:
                    nom: "Liste des campagnes"
                    niveau: "ROLE_VEILLE"
                    url: '/admin/techletter'
                techletter:
                    nom: 'Abonnés à la techletter'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/techletter/members'
                history:
                    nom: 'Historique de la techletter'
                    niveau: 'ROLE_VEILLE'
                    url: '/admin/techletter/history'
        site:
            nom: 'Site'
            niveau: 'ROLE_SITE'
            icon: "paint brush"
            elements:
                site_feuilles:
                    nom: 'Feuilles'
                    niveau: 'ROLE_SITE'
                site_rubriques:
                    nom: 'Rubriques'
                    niveau: 'ROLE_SITE'
                site_articles:
                    nom: 'Articles'
                    niveau: 'ROLE_SITE'
        antenne:
            nom: 'Antennes AFUP'
            niveau: 'ROLE_ANTENNE'
            elements:
                rendez_vous:
                    nom: 'Rendez-vous'
                    niveau: 'ROLE_ANTENNE'
                antenne:
                    nom: 'Liste des antennes'
                    niveau: 'ROLE_ANTENNE'
        forum:
            nom: 'Forum'
            niveau: 'ROLE_FORUM'
            icon: "globe"
            elements:
                forum_gestion:
                    nom: 'Gestion forum'
                    niveau: 'ROLE_ADMIN'
                forum_salle:
                    nom: 'Gestion des salles'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/room'
                forum_suivi:
                    nom: 'Suivi'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/stats'
                forum_inscriptions:
                    nom: 'Inscriptions'
                    niveau: 'ROLE_FORUM'
                forum_pending_bankwires:
                    nom: 'Inscriptions - virements en attente'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/bankwires'
                admin_event_sponsor_ticket:
                    nom: 'Inscriptions sponsors'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/sponsor'
                admin_event_special_price:
                    nom: 'Inscriptions - prix custom'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/special_price'
                admin_event_prices:
                    nom: 'Inscriptions - liste des prix'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/prices'
                admin_event_speakers_management:
                    nom: 'Gestion documentaire des speakers'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/speakers-management'
                forum_facturation:
                    nom: "Factures d'événément"
                    niveau: 'ROLE_ADMIN'
                forum_sessions:
                    nom: 'Sessions'
                    niveau: 'ROLE_FORUM'
                forum_vote_github:
                    nom: 'Sessions - votes visiteurs'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/vote/'
                forum_sessions_notees:
                    nom: 'Vote des sessions'
                    niveau: 'ROLE_FORUM'
                forum_conferenciers:
                    nom: 'Conférenciers'
                    niveau: 'ROLE_FORUM'
                forum_planning:
                    nom: 'Planning'
                    niveau: 'ROLE_FORUM'
                forum_joind_in:
                    nom: 'Export sites externes'
                    niveau: 'ROLE_ADMIN'
                forum_partenaire:
                    nom: 'Sponsors/Partenaires'
                    niveau: 'ROLE_ADMIN'
                forum_anonymous_export:
                    nom: 'Export anonymisé'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/export'
        annuaire:
            nom: 'Annuaire pro'
            niveau: 'ROLE_ANNUAIRE'
            elements:
                annuairepro_membres:
                    nom: 'Membres'
                    niveau: 'ROLE_ANNUAIRE'
        tresorerie:
            nom: 'Trésorerie'
            niveau: 'ROLE_ADMIN'
            icon: "money bill alternate"
            elements:
                compta_devis:
                    nom: 'Devis'
                    niveau: 'ROLE_ADMIN'
                compta_facture:
                    nom: 'Factures'
                    niveau: 'ROLE_ADMIN'
                compta_journal:
                    nom: 'Journal'
                    niveau: 'ROLE_ADMIN'
                compta_banque:
                    nom: 'Compte Banques'
                    niveau: 'ROLE_ADMIN'
                compta_synthese:
                    nom: 'Synthese Evenement'
                    niveau: 'ROLE_ADMIN'
                compta_balance:
                    nom: 'Balance comptable'
                    niveau: 'ROLE_ADMIN'
                compta_bilan:
                    nom: 'Bilan'
                    niveau: 'ROLE_ADMIN'
                compta_conf_evenement:
                    nom: 'Configuration'
                    niveau: 'ROLE_ADMIN'
                compta_recherche:
                    nom: 'Recherche comptable'
                    niveau: 'ROLE_ADMIN'
        planete:
            nom: 'Planète PHP FR'
            niveau: 'ROLE_ADMIN'
            icon: "rss"
            elements:
                planete_flux:
                    nom: 'Flux'
                    niveau: 'ROLE_ADMIN'

                planete_billet:
                    nom: 'Billets'
                    niveau: 'ROLE_ADMIN'
        divers:
            nom: 'Divers'
            niveau: 'ROLE_ADMIN'
            icon: "tag"
            elements:
                configuration:
                    nom: 'Configuration'
                    niveau: 'ROLE_ADMIN'
                membre_administrateur:
                    nom: 'Administrateurs du site'
                    niveau: 'ROLE_ADMIN'
                logs:
                    nom: 'Logs'
                    niveau: 'ROLE_ADMIN'
                info_serveur:
                    nom: 'Information serveur'
                    niveau: 'ROLE_ADMIN'
        connexion:
            nom: 'Connexion'
            masquee: true
            niveau: 'ROLE_USER'
        inscription:
            nom: 'Inscription'
            masquee: true
            niveau: 'ROLE_USER'
    paybox_ips:
        - '194.2.122.158'
        - '194.2.122.190'
        - '194.2.160.64'
        - '194.2.160.66'
        - '194.2.160.75'
        - '194.2.160.80'
        - '194.2.160.82'
        - '194.2.160.91'
        - '195.101.99.73'
        - '195.101.99.76'
        - '195.25.67.0'
        - '195.25.67.11'
        - '195.25.67.2'
        - '195.25.67.22'
        - '195.25.7.146'
        - '195.25.7.157'
        - '195.25.7.159'
        - '195.25.7.166'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"], enabled: true }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        storage_id: session.storage.php_bridge
        handler_id: ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      photo_storage: '@AppBundle\CFP\PhotoStorage'
    form_themes: ['form_theme_help.html.twig']

ting:
    connections:
        main:
            namespace: CCMBenchmark\Ting\Driver\Mysqli
            charset: utf8mb4
            master:
                host:     "%database_host%"
                port:     "%database_port%"
                user:     "%database_user%"
                password: "%database_password%"
    repositories:
        event:
            namespace : AppBundle\Event\Model\Repository
            directory : "@AppBundle/Event/Model/Repository"
            options:
                default:
                    connection: main
                    database: '%database_name%'
        site:
            namespace : AppBundle\Site\Model\Repository
            directory : "@AppBundle/Site/Model/Repository"
            options:
                default:
                    connection: main
                    database: '%database_name%'
        association:
            namespace : AppBundle\Association\Model\Repository
            directory : "@AppBundle/Association/Model/Repository"
            options:
                default:
                    connection: main
                    database: '%database_name%'
        groups:
            namespace : AppBundle\Groups\Model\Repository
            directory : "@AppBundle/Groups/Model/Repository"
            options:
                default:
                    connection: main
                    database: '%database_name%'
        throttling:
            namespace : AppBundle\Security\ActionThrottling
            directory : "@AppBundle/Security/ActionThrottling"
            options:
                default:
                    connection: main
                    database: '%database_name%'
        techletter:
            namespace: AppBundle\TechLetter\Model\Repository
            directory: "@AppBundle/TechLetter/Model/Repository"
            options:
                default:
                    connection: main
                    database: "%database_name%"

knpu_oauth2_client:
    clients:
        # will create a service: knpu.oauth2.client.facebook_main
        github_main:
            type: github
            client_id: "%github_client_id%"
            client_secret: "%github_client_secret%"
            # see below
            redirect_route: connection_github_check
