parameters:
    database_host: dbtest
    database_port: 3306
    database_name: web
    database_user: afup
    database_password: afup
    github_authenticator: "AppBundle\\Security\\TestGithubAuthenticator"
    slack_url: "http://fake-slack-url"

    smtp_host: "mailcatcher"
    smtp_tls: 0
    smtp_username: ""
    smtp_password: ""
    smtp_port: 1025

services:
    AppBundle\Offices\OfficeFinder:
        class: AppBundle\Offices\NullOfficeFinder
        arguments: ['@geocoder']

    Afup\Tests\Support\PlanetePHP\FeedHttpClientFactory: ~
    planetephp.http_client:
        class: Symfony\Contracts\HttpClient\HttpClientInterface
        factory: '@Afup\Tests\Support\PlanetePHP\FeedHttpClientFactory'

    PlanetePHP\SymfonyFeedClient:
        arguments:
            $httpClient: '@planetephp.http_client'
