admin_accounting_accounts_list:
  path: /list
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\ListAccountAction}

admin_accounting_accounts_edit:
  path: /edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\EditAccountAction}
  requirements:
    id: '\d+'

admin_accounting_accounts_add:
  path: /add
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\AddAccountAction}

admin_accounting_accounts_archive:
  path: /archive/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\ArchiveAccountAction}
  requirements:
    id: '\d+'

admin_accounting_accounts_restore:
  path: /restore/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\RestoreAccountAction}
  requirements:
    id: '\d+'
