admin_accounting_categories_list:
  path: /list
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\ListCategoryAction}

admin_accounting_categories_add:
  path: /add
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\AddCategoryAction}

admin_accounting_categories_edit:
  path: /edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\EditCategoryAction}
  requirements:
    id: '\d+'
