admin_accounting_journal_delete:
  path: /delete/{id}
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\Journal\DeleteAction
  requirements:
    id: \d+

admin_accounting_journal_download:
  path: /download/{id}
  requirements:
    id: '\d+'
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\Journal\DownloadAttachmentAction
