parameters:
    app.pages_backoffice:
        accueil:
            nom: 'Accueil'
            niveau: 'ROLE_MEMBER_EXPIRED'
            url: '/admin'
            extra_routes:
                - admin_home
        membres:
            nom: 'Membres'
            niveau: 'ROLE_ADMIN'
            icon: 'user'
            elements:
                personnes_physiques:
                    nom: 'Personnes physiques'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/users'
                    extra_routes:
                        - admin_slack_members_check
                        - admin_members_user_list
                        - admin_members_user_add
                        - admin_members_user_edit
                personnes_morales:
                    nom: 'Personnes morales'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/companies'
                    extra_routes:
                        - admin_members_company_list
                        - admin_members_company_add
                        - admin_members_company_edit
                relances_personnes_physiques:
                    nom: 'Relances cotisations'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/association/relances/1'
                    extra_routes:
                        - admin_relances
                reporting:
                    nom: 'Reporting'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/reporting'
                    extra_routes:
                        - admin_members_reporting
                badges:
                    nom: 'Badges'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/badges'
                    extra_routes:
                        - admin_members_badges_index
                        - admin_members_badges_new
        veille:
            nom: "Veille"
            niveau: "ROLE_VEILLE"
            icon: 'bullhorn'
            elements:
                veille_ generer_campagne:
                    nom: "Campagnes"
                    niveau: "ROLE_VEILLE"
                    url: '/admin/techletter'
                    extra_routes:
                        - admin_techletter_index
                        - admin_techletter_generate
                techletter:
                    nom: 'Abonnés'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/techletter/members'
                    extra_routes:
                        - admin_techletter_members
                history:
                    nom: 'Historique'
                    niveau: 'ROLE_VEILLE'
                    url: '/admin/techletter/history'
                    extra_routes:
                        - admin_techletter_history
        site:
            nom: 'Site'
            niveau: 'ROLE_SITE'
            icon: "paint brush"
            elements:
                site_feuilles:
                    nom: 'Feuilles'
                    niveau: 'ROLE_SITE'
                    url : '/admin/site/feuilles'
                    extra_routes:
                        - admin_site_sheets_list
                        - admin_site_sheets_add
                        - admin_site_sheets_edit
                site_rubriques:
                    nom: 'Rubriques'
                    niveau: 'ROLE_SITE'
                    url : '/admin/site/rubriques'
                    extra_routes:
                        - admin_site_rubriques_list
                        - admin_site_rubriques_add
                        - admin_site_rubriques_edit
                site_articles:
                    nom: 'Articles'
                    niveau: 'ROLE_SITE'
                    url : '/admin/site/articles'
                    extra_routes:
                        - admin_site_articles_list
                        - admin_site_articles_add
                        - admin_site_articles_edit
        forum:
            nom: 'Évènements'
            niveau: 'ROLE_FORUM'
            icon: "globe"
            elements:
                forum_gestion:
                    nom: 'Liste'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/list'
                    extra_routes:
                        - admin_event_list
                        - admin_event_new
                        - admin_event_edit
                forum_salle:
                    nom: 'Salles'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/room'
                    extra_routes:
                        - admin_event_room
                forum_suivi:
                    nom: 'Suivi'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/stats'
                    extra_routes:
                        - admin_event_stats
                forum_inscriptions:
                    nom: 'Inscriptions'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/tickets'
                    extra_routes:
                        - admin_event_ticket_list
                        - admin_event_ticket_add
                        - admin_event_ticket_edit
                forum_pending_bankwires:
                    nom: 'Virements en attente'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/bankwires'
                    extra_routes:
                        - admin_event_pending_bankwires
                admin_event_sponsor_ticket:
                    nom: 'Tokens sponsors'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/sponsor'
                    extra_routes:
                        - admin_event_sponsor_ticket
                admin_event_special_price:
                    nom: 'Tokens visiteurs'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/event/special_price'
                    extra_routes:
                        - admin_event_special_price
                admin_event_prices:
                    nom: 'Tarifications'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/prices'
                    extra_routes:
                        - admin_event_prices
                        - admin_event_prices_add
                        - admin_event_prices_edit
                forum_facturation:
                    nom: "Factures d'évènement"
                    niveau: 'ROLE_ADMIN'
                talks:
                    nom: 'Conférences'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/talk/'
                    extra_routes:
                        - admin_talk_list
                        - admin_talk_add
                        - admin_talk_edit
                forum_vote_github:
                    nom: 'Votes visiteurs'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/votes/'
                    extra_routes:
                        - admin_event_votes
                forum_conferenciers:
                    nom: 'Speakers'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/speaker/'
                    extra_routes:
                        - admin_speaker_list
                        - admin_speaker_add
                        - admin_speaker_edit
                admin_event_speakers_management:
                    nom: 'Infos speakers'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/speakers-management'
                    extra_routes:
                        - admin_event_speakers_management
                admin_event_speakers_expenses:
                    nom: 'Justificatifs speakers'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/speakers-expenses'
                    extra_routes:
                        - admin_event_speakers_expenses
                forum_planning:
                    nom: 'Planning'
                    niveau: 'ROLE_FORUM'
                    url: '/admin/event/sessions'
                    extra_routes:
                        - admin_event_sessions
                        - admin_event_sessions_edit
                admin_github_user_list:
                    nom: 'Github Users'
                    url: '/admin/event/github-user'
                    extra_routes:
                        - admin_github_user_add
                        - admin_github_user_list
        tresorerie:
            nom: 'Trésorerie'
            niveau: 'ROLE_ADMIN'
            icon: "money bill alternate"
            elements:
                compta_devis:
                    nom: 'Devis'
                    url: '/admin/accounting/quotations/list'
                    niveau: 'ROLE_ADMIN'
                    extra_routes:
                        - admin_accounting_quotations_list
                compta_facture:
                    nom: 'Factures'
                    url: '/admin/accounting/invoices/list'
                    niveau: 'ROLE_ADMIN'
                    extra_routes:
                        - admin_accounting_invoices_list
                compta_journal:
                    nom: 'Journal'
                    url: '/admin/accounting/journal/list'
                    niveau: 'ROLE_ADMIN'
                    extra_routes:
                        - admin_accounting_journal_list
                        - admin_accounting_journal_add
                        - admin_accounting_journal_edit
                        - admin_accounting_journal_import
                compta_conf_evenement:
                    nom: 'Configuration'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/accounting/configuration/events/list'
                    extra_routes:
                        - admin_accounting_events_list
                        - admin_accounting_categories_list
                        - admin_accounting_operations_list
                        - admin_accounting_payments_list
                        - admin_accounting_accounts_list
                        - admin_accounting_rules_list
                compta_recherche:
                    nom: 'Recherche comptable'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/accounting/search'
                    extra_routes:
                        - admin_accounting_search
        assemblee_generale:
            nom: 'Assemblée générale'
            niveau: 'ROLE_ADMIN'
            icon: 'comments'
            elements:
                assemblee_generale_infos:
                    nom: 'Informations'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/general_meeting'
                    extra_routes:
                        - admin_members_general_meeting
                        - admin_members_general_meeting_prepare
                        - admin_members_general_meeting_edit
                        - admin_members_general_meeting_reports
                assemblee_generale_votes:
                    nom: 'Votes'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/members/general_meeting_vote'
                    extra_routes:
                        - admin_members_general_vote_list
                        - admin_members_general_question_add
                        - admin_members_general_question_edit
        planete:
            nom: 'Planète PHP FR'
            niveau: 'ROLE_ADMIN'
            icon: "rss"
            elements:
                planete_flux:
                    nom: 'Flux'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/planete/feeds'
                    extra_routes:
                        - admin_planete_feed_list
                        - admin_planete_feed_add
                        - admin_planete_feed_edit

                planete_billet:
                    nom: 'Billets'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/planete/feed-articles'
                    extra_routes:
                        - admin_planete_feed_article_list
        antenne:
            nom: 'Antennes'
            niveau: 'ROLE_ADMIN'
            icon: 'map marker alternate piece'
            elements:
                antennes_index:
                    nom: 'Liste'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/antennes'
                    extra_routes:
                        - admin_antennes_list
        divers:
            nom: 'Divers'
            niveau: 'ROLE_ADMIN'
            icon: "tag"
            elements:
                membre_administrateur:
                    nom: 'Administrateurs du site'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/administrators'
                    extra_routes:
                        - admin_administrators
                logs:
                    nom: 'Logs'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/logs'
                    extra_routes:
                        - admin_logs
                healthcheck:
                    nom: 'Healthcheck'
                    niveau: 'ROLE_ADMIN'
                    url: '/admin/healthcheck'
                    extra_routes:
                        - admin_healthcheck
        connexion:
            nom: 'Connexion'
            masquee: true
            niveau: 'ROLE_USER'
        inscription:
            nom: 'Inscription'
            masquee: true
            niveau: 'ROLE_USER'
