framework:
    http_client:
        scoped_clients:
            http_client.github:
                base_uri: 'https://api.github.com'
                headers:
                    Accept: 'application/vnd.github.v3+json'
            http_client.meetup:
                base_uri: 'https://api.meetup.com'
                headers:
                    Content-Type: 'application/json'
            http_client.bluesky:
                base_uri: 'https://bsky.social'
