knpu_oauth2_client:
    clients:
        # will create a service: knpu.oauth2.client.facebook_main
        github_main:
            type: github
            client_id: "%env(GITHUB_CLIENT_ID)%"
            client_secret: "%env(GITHUB_CLIENT_SECRET)%"
            # see below
            redirect_route: connection_github_check
