parameters:
    locale: fr
    github_authenticator: "AppBundle\\Security\\GithubAuthenticator"
    paybox_ips:
        - '194.2.122.158'
        - '194.2.122.190'
        - '194.2.160.64'
        - '194.2.160.66'
        - '194.2.160.75'
        - '194.2.160.80'
        - '194.2.160.82'
        - '194.2.160.91'
        - '195.101.99.73'
        - '195.101.99.76'
        - '195.25.67.0'
        - '195.25.67.11'
        - '195.25.67.2'
        - '195.25.67.22'
        - '195.25.7.146'
        - '195.25.7.157'
        - '195.25.7.159'
        - '195.25.7.166'
