admin_vote:
  path: /vote/{eventSlug}
  requirements:
    eventSlug: .*
  defaults: {_controller: AppBundle:Vote:admin}

admin_relances:
  path: /association/relances/{page}
  defaults: {_controller: AppBundle:AdminMemberShip:reminderLog}

admin_void:
  path: /void
  defaults: {_controller: AppBundle:Legacy:backOffice}

admin_login:
  path: /login
  defaults: {_controller: AppBundle:Admin:login}

admin_logout:
  path: /logout

legacy_inscription:
  path: /register
  defaults: {_controller: AppBundle:Legacy:register}

admin_password:
  path: /password
  defaults: {_controller: AppBundle:Admin:lostPassword}

admin_event_routes:
    resource: "admin_event.yml"
    prefix: /event

admin_company:
  path: /company
  defaults: {_controller: AppBundle:AdminMemberShip:company}

admin_company_members:
  path: /company/members/{id}
  defaults: {_controller: AppBundle:AdminMemberShip:members, id: ~}

admin_members_reporting:
  path: /members/reporting
  defaults: {_controller: AppBundle:MembershipAdmin:reporting}
