admin_site_rubriques_list:
  path: /rubriques
  defaults: {_controller: AppBundle\Controller\Admin\Site\ListRubriquesAction}

admin_site_rubriques_add:
  path: /rubriques/add
  defaults: {_controller: AppBundle\Controller\Admin\Site\AddRubriqueAction}
  
admin_site_rubriques_edit:
  path: /rubriques/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Site\EditRubriqueAction}
  requirements:
    id: '\d+'

admin_site_rubriques_delete:
  path: /rubriques/delete/{id}/{token}
  defaults: {_controller: AppBundle\Controller\Admin\Site\DeleteRubriqueAction}
  requirements:
    id: '\d+'

admin_site_articles_list:
  path: /articles
  defaults: {_controller: AppBundle\Controller\Admin\Site\Article\ListArticlesAction}

admin_site_articles_add:
  path: /articles/add
  defaults: {_controller: AppBundle\Controller\Admin\Site\Article\AddArticleAction}

admin_site_articles_edit:
  path: /articles/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Site\Article\EditArticleAction}
  requirements:
    id: '\d+'

admin_site_articles_delete:
  path: /articles/delete/{id}/{token}
  defaults: {_controller: AppBundle\Controller\Admin\Site\Article\DeleteArticleAction}
  requirements:
    id: '\d+'

admin_site_sheets_list:
  path: /feuilles
  defaults: {_controller: AppBundle\Controller\Admin\Site\Sheet\ListSheetsAction}

admin_site_sheets_add:
  path: /feuilles/add
  defaults: {_controller: AppBundle\Controller\Admin\Site\Sheet\AddSheetAction}

admin_site_sheets_edit:
  path: /feuilles/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Site\Sheet\EditSheetAction}
  requirements:
    id: '\d+'

admin_site_sheets_delete:
  path: /feuilles/delete/{id}/{token}
  defaults: {_controller: AppBundle\Controller\Admin\Site\Sheet\DeleteSheetAction}
  requirements:
    id: '\d+'
