admin_accounting_accounts_list:
  path: /accounts/list
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\ListAccountAction}

admin_accounting_accounts_edit:
  path: /accounts/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\EditAccountAction}
  requirements:
    id: '\d+'

admin_accounting_accounts_add:
  path: /accounts/add
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\AddAccountAction}

admin_accounting_accounts_archive:
  path: /accounts/archive/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\ArchiveAccountAction}
  requirements:
    id: '\d+'

admin_accounting_accounts_restore:
  path: /accounts/restore/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\RestoreAccountAction}
  requirements:
    id: '\d+'

admin_accounting_operations_list:
  path: /operations/list
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\ListOperationAction}

admin_accounting_operations_add:
  path: /operations/add
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\AddOperationAction}

admin_accounting_operations_edit:
  path: /operations/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Accounting\Configuration\EditOperationAction}
  requirements:
    id: '\d+'
