admin_accounting_bank_accounts_list:
  path: /list
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\BankAccounts\ListStatementAction

admin_accounting_bankaccounts_export:
  path: /export
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\BankAccounts\ExportStatementAction
