admin_github_user_list:
  path: /
  defaults: {_controller: AppBundle\Controller\Admin\GithubUser\GithubUserListAction}

admin_github_user_add:
  path: /add
  defaults: {_controller: AppBundle\Controller\Admin\GithubUser\GithubUserAddAction}
