admin_accounting_bank_accounts_list:
  path: /list
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\BankAccounts\ListStatementAction


admin_accounting_bank_accounts_download:
  path: /download-statements
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\BankAccounts\DownloadStatementAction
