admin_event_room:
  path: /room
  defaults: {_controller: AppBundle:AdminEvent:room}

admin_event_sponsor_ticket:
  path: /sponsor
  defaults: {_controller: AppBundle:AdminEvent:sponsorTicket}

admin_event_sponsor_mail:
  path: /sponsor/mail
  defaults: {_controller: AppBundle:AdminEvent:resendSponsorToken}

admin_event_sponsor_lastcall_mail:
  path: /sponsor/lastcall
  defaults: {_controller: AppBundle:AdminEvent:sendLastCallSponsorToken}

admin_event_stats:
  path: /stats
  defaults: {_controller: AppBundle:AdminEvent:stats}

export_anonymous:
  path: /export
  defaults: {_controller: AppBundle:AdminEvent:exportAnonymousData}

admin_event_pending_bankwires:
  path: /bankwires
  defaults: {_controller: AppBundle:AdminEvent:pendingBankwires}

admin_event_speakers_management:
  path: /speakers-management
  defaults: {_controller: AppBundle:AdminEvent:speakersManagement}

admin_event_special_price:
  path: /special_price
  defaults: {_controller: AppBundle:AdminEvent:specialPrice}

admin_event_speaker_infos:
  path: /speaker-infos
  defaults: {_controller: AppBundle:AdminEvent:speakerInfos}

admin_event_send_test_mail_inscription:
  path: /send-test-mail-inscription
  defaults: {_controller: AppBundle:AdminEvent:sendTestInscriptionEmail}

admin_event_badges:
  path: /badges
  defaults: {_controller: AppBundle:AdminEvent:badgesGenerate}

admin_event_previous_registrations:
  path: /previous_registrations
  defaults: {_controller: AppBundle:AdminEvent:previousRegistrations}
