admin_event_list:
  path: /list
  defaults: {_controller: AppBundle\Controller\Admin\Event\ListAction}

admin_event_delete:
  path: /delete/{id}/{token}
  defaults: {_controller: AppBundle\Controller\Admin\Event\RemoveEventAction}
  requirements:
    id: \d+

admin_event_new:
  path: /new
  defaults:
    _controller: AppBundle\Controller\Admin\Event\EventAction
    id: null

admin_event_edit:
  path: /edit/{id}
  defaults:
    _controller: AppBundle\Controller\Admin\Event\EventAction
  requirements:
    id: \d+

admin_event_room:
  path: /room
  defaults: {_controller: AppBundle\Controller\Admin\Event\RoomAction}

admin_event_sponsor_ticket:
  path: /sponsor
  defaults: {_controller: AppBundle\Controller\Admin\Event\SponsorTicketAction}

admin_event_sponsor_mail:
  path: /sponsor/mail
  defaults: {_controller: AppBundle\Controller\Admin\Event\ResendSponsorTokenAction}

admin_event_sponsor_lastcall_mail:
  path: /sponsor/lastcall
  defaults: {_controller: AppBundle\Controller\Admin\Event\SendLastCallSponsorTokenAction}

admin_event_stats:
  path: /stats
  defaults: {_controller: AppBundle\Controller\Admin\Event\StatsAction}

admin_event_pending_bankwires:
  path: /bankwires
  defaults: {_controller: AppBundle\Controller\Admin\Event\PendingBankwiresAction}

admin_event_speakers_management:
  path: /speakers-management
  defaults: {_controller: AppBundle\Controller\Admin\Event\SpeakersManagementAction}

admin_event_speakers_expenses:
  path: /speakers-expenses
  defaults: {_controller: AppBundle\Controller\Admin\Event\SpeakersExpensesAction}

admin_event_special_price:
  path: /special_price
  defaults: {_controller: AppBundle\Controller\Admin\Event\SpecialPriceAction}

admin_event_prices:
  path: /prices
  defaults: {_controller: AppBundle\Controller\Admin\Event\PricesAction }

admin_event_prices_add:
  path: /prices/add
  defaults: {_controller: AppBundle\Controller\Admin\Event\PricesAddAction}

admin_event_prices_edit:
  path: /prices/edit/{event}/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Event\PricesEditAction}
  requirements:
    event: \d+
    id: \d+

admin_event_speaker_infos:
  path: /speaker-infos
  defaults: {_controller: AppBundle\Controller\Admin\Event\SpeakerInfosAction }

admin_event_send_test_mail_inscription:
  path: /send-test-mail-inscription/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Event\SendTestInscriptionEmailAction }
  requirements:
    id: \d+

admin_event_badges:
  path: /badges
  defaults: {_controller: AppBundle\Controller\Admin\Event\BadgesGenerateAction }

admin_event_previous_registrations:
  path: /previous_registrations
  defaults: {_controller: AppBundle\Controller\Admin\Event\PreviousRegistrationsAction }

admin_event_archive:
  path: /archive/{id}
  defaults: { _controller: AppBundle\Controller\Admin\Event\ArchiveAction }
  requirements:
    id: \d+

admin_event_restore:
  path: /restore/{id}
  defaults: { _controller: AppBundle\Controller\Admin\Event\RestoreAction }
  requirements:
    id: \d+
