admin_home:
  path: /
  defaults: {_controller: AppBundle\Controller\Admin\HomeAction}

admin_vote:
  path: /vote/
  defaults: {_controller: AppBundle:Vote:admin}

admin_relances:
  path: /association/relances/{page}
  defaults: {_controller: AppBundle\Controller\Admin\Membership\ReminderLogAction}

admin_void:
  path: /void
  defaults: {_controller: AppBundle:Legacy:backOffice}

admin_login:
  path: /login
  defaults: {_controller: AppBundle\Controller\Admin\LoginAction}

admin_logout:
  path: /logout

legacy_inscription:
  path: /register
  defaults: {_controller: AppBundle:Legacy:register}

admin_password:
  path: /password
  defaults: {_controller: AppBundle\Controller\Admin\LostPasswordAction}

admin_members:
    resource: "admin_members.yml"
    prefix: /members

admin_event_routes:
    resource: "admin_event.yml"
    prefix: /event

admin_talk_routes:
  resource: "admin_talk.yml"
  prefix: /talk

admin_speaker_routes:
  resource: "admin_speaker.yml"
  prefix: /speaker

member_slack_invite:
  path: /member/slack-invite
  defaults: {_controller: AppBundle:MemberShip:slackInviteRequest}

admin_members_reporting:
  path: /members/reporting
  defaults: {_controller: AppBundle\Controller\MembershipAdmin\ReportingAction}

admin_members_general_meeting:
  path: /members/general_meeting
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\ListAction}

admin_members_general_meeting_prepare:
  path: /members/general_meeting/prepare
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\PrepareAction}

admin_members_general_meeting_listing:
  path: /members/general_meeting/listing
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\ListingAction}

admin_techletter:
  resource: "techletter_admin.yml"
  prefix: /techletter

admin_slack_members_check:
  path: /slackmembers/check
  defaults: {_controller: AppBundle\Controller\Admin\SlackMembers\CheckMembersAction }
