admin_home:
  path: /
  defaults: {_controller: AppBundle\Controller\Admin\HomeAction}

admin_vote:
  path: /vote/
  defaults: {_controller: AppBundle\Controller\Admin\VoteController::admin}

admin_relances:
  path: /association/relances/{page}
  defaults: {_controller: AppBundle\Controller\Admin\Membership\ReminderLogAction}

admin_void:
  path: /void
  defaults: {_controller: AppBundle\Controller\LegacyController::backOffice}

admin_login:
  path: /login
  defaults: {_controller: AppBundle\Controller\Admin\LoginAction}

admin_logout:
  path: /logout

admin_password:
  path: /password
  defaults: {_controller: AppBundle\Controller\Admin\LostPasswordAction}

admin_members:
    resource: "admin_members.yml"
    prefix: /members

admin_event_routes:
    resource: "admin_event.yml"
    prefix: /event

admin_talk_routes:
  resource: "admin_talk.yml"
  prefix: /talk

admin_speaker_routes:
  resource: "admin_speaker.yml"
  prefix: /speaker

admin_planete_routes:
  resource: "admin_planete.yml"
  prefix: /planete

admin_members_reporting:
  path: /members/reporting
  defaults: {_controller: AppBundle\Controller\MembershipAdmin\ReportingAction}

admin_members_general_meeting:
  path: /members/general_meeting
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\ListAction}

admin_members_general_meeting_prepare:
  path: /members/general_meeting/prepare
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\PrepareAction}

admin_members_general_meeting_edit:
  path: /members/general_meeting/edit
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\EditAction}

admin_members_general_meeting_listing:
  path: /members/general_meeting/listing
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\ListingAction}

admin_members_general_vote_list:
  path: /members/general_meeting_vote
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeetingVote\ListAction}

admin_members_general_question_add:
  path: /members/general_meeting_question/{date}/add
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeetingQuestion\AddAction}

admin_members_general_question_edit:
  path: /members/general_meeting_question/{id}/edit
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeetingQuestion\EditAction}

admin_members_general_question_delete:
  path: /members/general_meeting_question/{id}/delete
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeetingQuestion\DeleteAction}

admin_members_general_vote_open:
  path: /members/general_meeting_vote/open
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeetingVote\OpenAction}

admin_members_general_vote_close:
  path: /members/general_meeting_vote/close
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeetingVote\CloseAction}

admin_members_general_meeting_reports:
  path: /members/general_meeting/reports
  defaults: {_controller: AppBundle\Controller\Admin\Members\GeneralMeeting\ReportsAction}

admin_techletter:
  resource: "techletter_admin.yml"
  prefix: /techletter

admin_slack_members_check:
  path: /slackmembers/check
  defaults: {_controller: AppBundle\Controller\Admin\SlackMembers\CheckMembersAction }

admin_site:
  resource: "admin_site.yml"
  prefix: /site

admin_github_user_routes:
  resource: "admin_github_user.yml"
  prefix: /event/github-user
