admin_vote:
  path: /vote/{eventSlug}
  requirements:
    eventSlug: .*
  defaults: {_controller: AppBundle:Vote:admin}

admin_relances:
  path: /association/relances/{page}
  defaults: {_controller: AppBundle:AdminMemberShip:reminderLog}

admin_void:
  path: /void
  defaults: {_controller: AppBundle:Legacy:backOffice}

admin_login:
  path: /login
  defaults: {_controller: AppBundle:Admin:login}

admin_logout:
  path: /logout

legacy_inscription:
  path: /register
  defaults: {_controller: AppBundle:Legacy:register}

admin_password:
  path: /password
  defaults: {_controller: AppBundle:Admin:lostPassword}

admin_event_routes:
    resource: "admin_event.yml"
    prefix: /event

admin_talk_routes:
  resource: "admin_talk.yml"
  prefix: /talk

admin_speaker_routes:
  resource: "admin_speaker.yml"
  prefix: /speaker

admin_company:
  path: /company
  defaults: {_controller: AppBundle:AdminMemberShip:company}

admin_company_members:
  path: /company/members/{id}
  defaults: {_controller: AppBundle:AdminMemberShip:members, id: ~}

member_slack_invite:
  path: /member/slack-invite
  defaults: {_controller: AppBundle:MemberShip:slackInviteRequest}

admin_members_reporting:
  path: /members/reporting
  defaults: {_controller: AppBundle:MembershipAdmin:reporting}

admin_techletter:
  resource: "techletter_admin.yml"
  prefix: /techletter

member_contact:
  path: /member/contact
  defaults: {_controller: AppBundle:MemberShip:contactDetails}


member_membership_fee:
  path: /member/membership-fee
  defaults: {_controller: AppBundle:MemberShip:membershipFee}
