admin_talk_list:
  path: /
  defaults: {_controller: AppBundle\Controller\Admin\Talk\IndexAction}

admin_talk_export_joind_in:
  path: /export/joind-in/{eventId}/
  defaults: {_controller: AppBundle\Controller\Admin\Talk\ExportJoindInAction}
  requirements:
    event_id: \d+

admin_talk_export:
  path: /export
  defaults: {_controller: AppBundle\Controller\Admin\Talk\ExportAction}

admin_talk_indexation:
  path: /update_indexation
  defaults: {_controller: AppBundle\Controller\Admin\Talk\UpdateIndexationAction}
