public_payment_invoice:
  path: /facture/
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\Invoice\PublicPaymentAction

public_download_invoice:
  path: /facture/download/
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\Invoice\PublicDownloadAction

public_payment_redirect:
  path: /{type}/
  defaults:
    _controller: AppBundle\Controller\Admin\Accounting\Invoice\PublicPaymentRedirectAction
    type: success
  requirements:
    type: success|error|canceled|refused